name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build & publish Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: sencha/6.2.0.103
            tag: fuadkleb/sencha-cmd:6.2.0.103
            platforms: linux/amd64,linux/arm64
          - context: sencha/7.3.0.19
            tag: fuadkleb/sencha-cmd:7.3.0.19
            platforms: linux/amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          # Use a Docker Hub PAT, not your account password
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (and push if not PR)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.tag }}
          platforms: ${{ matrix.platforms }}
          # GitHub Actions cache for faster rebuilds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Optional: disable SBOM/provenance if you don't need them
          # sbom: false
          # provenance: false
